// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxnklgylctuyucgljkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueG5rbGd5bGN0dXl1Y2dsamt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzg0MzEsImV4cCI6MjA2MzY1NDQzMX0.zthCrGcUpEiHefYMXIqf4_-raz5uxh19KI8u0WTYsSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);